// AUTO-GENERATED by scripts/generate-cost-model.mjs — do not hand-edit.
// Regenerated automatically by `npm run build`'s "prebuild" script, derived
// from the REAL src/commands/*.ts source (grep for `gatePaidCall(`) — REQ-PACK-001.
// Committed to git (REQ-PACK-004): npm test runs directly against source with no
// prior build step, so a gitignored file would be absent on a fresh clone.
// test/unit/cost-model-generated-parity.test.ts fails if this ever drifts from the
// real source.
export type CostModel = "free" | "paid";

export const COMMAND_COST_MODEL: Record<string, CostModel> = {
  "chat": "paid",
  "defi": "paid",
  "dex": "free",
  "exa": "paid",
  "image": "paid",
  "markets": "paid",
  "modal": "paid",
  "models": "free",
  "music": "paid",
  "phone": "paid",
  "price": "paid",
  "realface": "paid",
  "rpc": "paid",
  "search": "paid",
  "speech": "paid",
  "surf": "paid",
  "video": "paid",
  "wallet": "free",
};
